// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzitpimnrvbghywqazke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6aXRwaW1ucnZiZ2h5d3FhemtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTA1NzAsImV4cCI6MjA2OTM2NjU3MH0.gXqIBXyoZWErG9nQ1mXKplnbWbLHHaP5k2tGFaVGAw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});